name: Sphinx

on: [push]

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
        - name: Install Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.10.0
        - name: Install dependencies
          run:
            python -m pip install --upgrade pip
            pip install sphinx
            pip install sphinx_rtd_theme
        - uses: actions/checkout@v1
        - uses: ammaraskar/sphinx-action@master
          with:
            docs-folder: "docs/"
            build-command: "sphinx-build -b html . _build"
